---@class ShortcutsWindow : Object
local ShortcutsWindow = extends "object"

ShortcutsWindow.name = "Shortcuts"

function ShortcutsWindow:draw()
	imgui.Begin(ShortcutsWindow.name)
	imgui.Text "TESTSETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
	imgui.Text "TESTSETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
	imgui.Text "TESTSETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
	imgui.Text "TESTSETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
	imgui.Text "TESTSETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
	imgui.End()
end

return ShortcutsWindow